#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActivityBrowserRow

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ActivityBrowserRow.ActivityBrowserRow_C
// 0x0000 (0x0270 - 0x0270)
class UActivityBrowserRow_C final : public UFortActivityBrowserRow
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ActivityBrowserRow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ActivityBrowserRow_C")
	}
	static class UActivityBrowserRow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActivityBrowserRow_C>();
	}
};
DUMPER7_ASSERTS_UActivityBrowserRow_C;

}

