#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaBattlePassRewardDetails

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaBattlePassRewardDetails.AthenaBattlePassRewardDetails_C
// 0x0018 (0x0248 - 0x0230)
class UAthenaBattlePassRewardDetails_C final : public UBattlePassScreenRewardDetails
{
public:
	class UDynamicEntryBox*                       DynamicEntryBox;                                   // 0x0230(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDynamicEntryBox*                       DynamicEntryBox_71;                                // 0x0238(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           StyleListContainer;                                // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AthenaBattlePassRewardDetails_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AthenaBattlePassRewardDetails_C")
	}
	static class UAthenaBattlePassRewardDetails_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaBattlePassRewardDetails_C>();
	}
};
DUMPER7_ASSERTS_UAthenaBattlePassRewardDetails_C;

}

