#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_PlayerCameraModeTargetingHiInfantry

#include "Basic.hpp"

#include "Athena_PlayerCameraModeRangedTargeting_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_PlayerCameraModeTargetingHiInfantry.Athena_PlayerCameraModeTargetingHiInfantry_C
// 0x0000 (0x0CF0 - 0x0CF0)
class UAthena_PlayerCameraModeTargetingHiInfantry_C final : public UAthena_PlayerCameraModeRangedTargeting_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Athena_PlayerCameraModeTargetingHiInfantry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Athena_PlayerCameraModeTargetingHiInfantry_C")
	}
	static class UAthena_PlayerCameraModeTargetingHiInfantry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthena_PlayerCameraModeTargetingHiInfantry_C>();
	}
};
DUMPER7_ASSERTS_UAthena_PlayerCameraModeTargetingHiInfantry_C;

}

