#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_PlayerCameraModeInfantry

#include "Basic.hpp"

#include "Athena_PlayerCameraModeBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_PlayerCameraModeInfantry.Athena_PlayerCameraModeInfantry_C
// 0x0000 (0x0CF0 - 0x0CF0)
class UAthena_PlayerCameraModeInfantry_C final : public UAthena_PlayerCameraModeBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Athena_PlayerCameraModeInfantry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Athena_PlayerCameraModeInfantry_C")
	}
	static class UAthena_PlayerCameraModeInfantry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthena_PlayerCameraModeInfantry_C>();
	}
};
DUMPER7_ASSERTS_UAthena_PlayerCameraModeInfantry_C;

}

