#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Athena_Booty_Item

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "B_UtilityItem_Generic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Athena_Booty_Item.B_Athena_Booty_Item_C
// 0x0010 (0x0950 - 0x0940)
class AB_Athena_Booty_Item_C final : public AB_UtilityItem_Generic_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0940(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Map;                                               // 0x0948(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_Athena_Booty_Item(int32 EntryPoint);
	void K2_OnUnEquip();
	void OnWeaponAttached();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("B_Athena_Booty_Item_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"B_Athena_Booty_Item_C")
	}
	static class AB_Athena_Booty_Item_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Athena_Booty_Item_C>();
	}
};
DUMPER7_ASSERTS_AB_Athena_Booty_Item_C;

}

