#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Hookgun_Athena

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "B_Ranged_Generic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Hookgun_Athena.B_Hookgun_Athena_C
// 0x0018 (0x0EA0 - 0x0E88)
class AB_Hookgun_Athena_C final : public AB_Ranged_Generic_C
{
public:
	uint8                                         Pad_E84[0x4];                                      // 0x0E84(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           Timer;                                             // 0x0E88(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerPawnAthena*                  Player_Pawn;                                       // 0x0E90(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Debug;                                             // 0x0E98(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("B_Hookgun_Athena_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"B_Hookgun_Athena_C")
	}
	static class AB_Hookgun_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Hookgun_Athena_C>();
	}
};
DUMPER7_ASSERTS_AB_Hookgun_Athena_C;

}

