#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_MountedCannonAthena_InCannon

#include "Basic.hpp"

#include "B_MountedCannonAthena_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_MountedCannonAthena_InCannon.B_MountedCannonAthena_InCannon_C
// 0x0000 (0x0E48 - 0x0E48)
class AB_MountedCannonAthena_InCannon_C final : public AB_MountedCannonAthena_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("B_MountedCannonAthena_InCannon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"B_MountedCannonAthena_InCannon_C")
	}
	static class AB_MountedCannonAthena_InCannon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_MountedCannonAthena_InCannon_C>();
	}
};
DUMPER7_ASSERTS_AB_MountedCannonAthena_InCannon_C;

}

