#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Pistol_Flashlight

#include "Basic.hpp"

#include "B_Pistol_Vigilante_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Pistol_Flashlight.B_Pistol_Flashlight_C
// 0x0018 (0x0EA0 - 0x0E88)
class AB_Pistol_Flashlight_C final : public AB_Pistol_Vigilante_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_Pistol_Flashlight_C;              // 0x0E88(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Sm_CreativeMoveTool_Lightbeam;                     // 0x0E90(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight;                                         // 0x0E98(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_Pistol_Flashlight(int32 EntryPoint);
	void OnWeaponAttached();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("B_Pistol_Flashlight_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"B_Pistol_Flashlight_C")
	}
	static class AB_Pistol_Flashlight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Pistol_Flashlight_C>();
	}
};
DUMPER7_ASSERTS_AB_Pistol_Flashlight_C;

}

