#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_WaterBuffalo_Athena

#include "Basic.hpp"

#include "B_ConsumableSmall_Athena_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_WaterBuffalo_Athena.B_WaterBuffalo_Athena_C
// 0x0008 (0x0948 - 0x0940)
class AB_WaterBuffalo_Athena_C final : public AB_ConsumableSmall_Athena_C
{
public:
	class USkeletalMeshComponentBudgeted*         RepositionedMesh;                                  // 0x0940(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("B_WaterBuffalo_Athena_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"B_WaterBuffalo_Athena_C")
	}
	static class AB_WaterBuffalo_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_WaterBuffalo_Athena_C>();
	}
};
DUMPER7_ASSERTS_AB_WaterBuffalo_Athena_C;

}

