#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BattlePassScreenTierList

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BattlePassScreenTierList.BattlePassScreenTierList_C
// 0x0008 (0x02C8 - 0x02C0)
class UBattlePassScreenTierList_C final : public UBattlePassScreenTierList
{
public:
	class UIconTextButton_C*                      Button_Purchase;                                   // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BattlePassScreenTierList_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BattlePassScreenTierList_C")
	}
	static class UBattlePassScreenTierList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBattlePassScreenTierList_C>();
	}
};
DUMPER7_ASSERTS_UBattlePassScreenTierList_C;

}

