#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CreaturePlacerRift

#include "Basic.hpp"

#include "BP_CreaturePlacerRift_classes.hpp"
#include "BP_CreaturePlacerRift_parameters.hpp"


namespace SDK
{

// Function BP_CreaturePlacerRift.BP_CreaturePlacerRift_C.ExecuteUbergraph_BP_CreaturePlacerRift
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CreaturePlacerRift_C::ExecuteUbergraph_BP_CreaturePlacerRift(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CreaturePlacerRift_C", "ExecuteUbergraph_BP_CreaturePlacerRift");

	Params::BP_CreaturePlacerRift_C_ExecuteUbergraph_BP_CreaturePlacerRift Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CreaturePlacerRift.BP_CreaturePlacerRift_C.BlueprintHideVFX
// (Event, Public, BlueprintEvent)

void ABP_CreaturePlacerRift_C::BlueprintHideVFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CreaturePlacerRift_C", "BlueprintHideVFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CreaturePlacerRift.BP_CreaturePlacerRift_C.BP_Cosmetic_Idle
// (Event, Protected, BlueprintEvent)

void ABP_CreaturePlacerRift_C::BP_Cosmetic_Idle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CreaturePlacerRift_C", "BP_Cosmetic_Idle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CreaturePlacerRift.BP_CreaturePlacerRift_C.BP_Cosmetic_Intro
// (Event, Protected, BlueprintEvent)

void ABP_CreaturePlacerRift_C::BP_Cosmetic_Intro()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CreaturePlacerRift_C", "BP_Cosmetic_Intro");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CreaturePlacerRift.BP_CreaturePlacerRift_C.BP_Cosmetic_RampUp
// (Event, Protected, BlueprintEvent)

void ABP_CreaturePlacerRift_C::BP_Cosmetic_RampUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CreaturePlacerRift_C", "BP_Cosmetic_RampUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CreaturePlacerRift.BP_CreaturePlacerRift_C.BP_Cosmetic_ShouldDie
// (Event, Protected, BlueprintEvent)

void ABP_CreaturePlacerRift_C::BP_Cosmetic_ShouldDie()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CreaturePlacerRift_C", "BP_Cosmetic_ShouldDie");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CreaturePlacerRift.BP_CreaturePlacerRift_C.HideSpawner
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_CreaturePlacerRift_C::HideSpawner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CreaturePlacerRift_C", "HideSpawner");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CreaturePlacerRift.BP_CreaturePlacerRift_C.OnStartedEncounterSpawn
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// class AFortAIPawn*                      SpawnedAI                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CreaturePlacerRift_C::OnStartedEncounterSpawn(class AFortAIPawn* SpawnedAI)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CreaturePlacerRift_C", "OnStartedEncounterSpawn");

	Params::BP_CreaturePlacerRift_C_OnStartedEncounterSpawn Parms{};

	Parms.SpawnedAI = SpawnedAI;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CreaturePlacerRift.BP_CreaturePlacerRift_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CreaturePlacerRift_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CreaturePlacerRift_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

