#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CreaturePlacerRift

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_CreativeDeimosRift_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CreaturePlacerRift.BP_CreaturePlacerRift_C
// 0x0008 (0x0D88 - 0x0D80)
class ABP_CreaturePlacerRift_C final : public ABP_CreativeDeimosRift_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_CreaturePlacerRift_C;            // 0x0D80(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_CreaturePlacerRift(int32 EntryPoint);
	void BlueprintHideVFX();
	void BP_Cosmetic_Idle();
	void BP_Cosmetic_Intro();
	void BP_Cosmetic_RampUp();
	void BP_Cosmetic_ShouldDie();
	void HideSpawner();
	void OnStartedEncounterSpawn(class AFortAIPawn* SpawnedAI);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CreaturePlacerRift_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CreaturePlacerRift_C")
	}
	static class ABP_CreaturePlacerRift_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CreaturePlacerRift_C>();
	}
};
DUMPER7_ASSERTS_ABP_CreaturePlacerRift_C;

}

