#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BulletWhipTrackerComponent_ProxGrenLauncher

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BulletWhipTrackerComponent_ProxGrenLauncher.BulletWhipTrackerComponent_ProxGrenLauncher_C
// 0x0000 (0x00E8 - 0x00E8)
class UBulletWhipTrackerComponent_ProxGrenLauncher_C final : public UBulletWhipTrackerComponentBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BulletWhipTrackerComponent_ProxGrenLauncher_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BulletWhipTrackerComponent_ProxGrenLauncher_C")
	}
	static class UBulletWhipTrackerComponent_ProxGrenLauncher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBulletWhipTrackerComponent_ProxGrenLauncher_C>();
	}
};
DUMPER7_ASSERTS_UBulletWhipTrackerComponent_ProxGrenLauncher_C;

}

