#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyle_Skew_Black

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Skew_Black.ButtonStyle-Skew_Black_C
// 0x0000 (0x0570 - 0x0570)
class UButtonStyle_Skew_Black_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ButtonStyle-Skew_Black_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ButtonStyle-Skew_Black_C")
	}
	static class UButtonStyle_Skew_Black_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_Skew_Black_C>();
	}
};
DUMPER7_ASSERTS_UButtonStyle_Skew_Black_C;

}

