#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChallengeDetailsRewardTrack

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ChallengeDetailsRewardTrack.ChallengeDetailsRewardTrack_C
// 0x0010 (0x0288 - 0x0278)
class UChallengeDetailsRewardTrack_C final : public UAthenaChallengeDetailRewardTrack
{
public:
	class UCommonActionWidget*                    CommonActionWidget_0;                              // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonActionWidget*                    CommonActionWidget_1;                              // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ChallengeDetailsRewardTrack_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ChallengeDetailsRewardTrack_C")
	}
	static class UChallengeDetailsRewardTrack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChallengeDetailsRewardTrack_C>();
	}
};
DUMPER7_ASSERTS_UChallengeDetailsRewardTrack_C;

}

