#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChallengeReward

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ChallengeReward.ChallengeReward_C
// 0x0000 (0x0238 - 0x0238)
class UChallengeReward_C final : public UAthenaChallengeRewardDisplay
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ChallengeReward_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ChallengeReward_C")
	}
	static class UChallengeReward_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChallengeReward_C>();
	}
};
DUMPER7_ASSERTS_UChallengeReward_C;

}

