#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChallengeDetailsListView

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ChallengeDetailsListView.ChallengeDetailsListView_C
// 0x0000 (0x0260 - 0x0260)
class UChallengeDetailsListView_C final : public UAthenaChallengeDetailList
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ChallengeDetailsListView_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ChallengeDetailsListView_C")
	}
	static class UChallengeDetailsListView_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChallengeDetailsListView_C>();
	}
};
DUMPER7_ASSERTS_UChallengeDetailsListView_C;

}

