#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: com_ButtonStyle_CloseTutorial

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass com_ButtonStyle_CloseTutorial.com_ButtonStyle_CloseTutorial_C
// 0x0000 (0x0570 - 0x0570)
class Ucom_ButtonStyle_CloseTutorial_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("com_ButtonStyle_CloseTutorial_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"com_ButtonStyle_CloseTutorial_C")
	}
	static class Ucom_ButtonStyle_CloseTutorial_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Ucom_ButtonStyle_CloseTutorial_C>();
	}
};
DUMPER7_ASSERTS_Ucom_ButtonStyle_CloseTutorial_C;

}

