#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ComOption

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ComOption.ComOption_C
// 0x0008 (0x02A0 - 0x0298)
class UComOption_C final : public UFortCommunityVotingOption
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void OnMouseLeave(const struct FPointerEvent& MouseEvent);
	void OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void EnableButtons();
	void DisableButtons();
	void Construct();
	void ExecuteUbergraph_ComOption(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ComOption_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ComOption_C")
	}
	static class UComOption_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UComOption_C>();
	}
};
DUMPER7_ASSERTS_UComOption_C;

}

