#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ComOption

#include "Basic.hpp"

#include "ComOption_classes.hpp"
#include "ComOption_parameters.hpp"


namespace SDK
{

// Function ComOption.ComOption_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UComOption_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ComOption_C", "OnMouseLeave");

	Params::ComOption_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ComOption.ComOption_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UComOption_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ComOption_C", "OnMouseEnter");

	Params::ComOption_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ComOption.ComOption_C.EnableButtons
// (Event, Public, BlueprintEvent)

void UComOption_C::EnableButtons()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ComOption_C", "EnableButtons");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ComOption.ComOption_C.DisableButtons
// (Event, Public, BlueprintEvent)

void UComOption_C::DisableButtons()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ComOption_C", "DisableButtons");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ComOption.ComOption_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UComOption_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ComOption_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ComOption.ComOption_C.ExecuteUbergraph_ComOption
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UComOption_C::ExecuteUbergraph_ComOption(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ComOption_C", "ExecuteUbergraph_ComOption");

	Params::ComOption_C_ExecuteUbergraph_ComOption Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

