#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ComScreenTileTab

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ComScreenTileTab.ComScreenTileTab_C
// 0x0010 (0x0258 - 0x0248)
class UComScreenTileTab_C final : public UFortCommunityVotingTab
{
public:
	class UImage*                                 Clock_2;                                           // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_LargeTile_1;                         // 0x0250(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ComScreenTileTab_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ComScreenTileTab_C")
	}
	static class UComScreenTileTab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UComScreenTileTab_C>();
	}
};
DUMPER7_ASSERTS_UComScreenTileTab_C;

}

