#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ComWinnerTab

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ComWinnerTab.ComWinnerTab_C
// 0x0008 (0x0250 - 0x0248)
class UComWinnerTab_C final : public UFortCommunityVotingTab
{
public:
	class UImage*                                 Clock_2;                                           // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ComWinnerTab_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ComWinnerTab_C")
	}
	static class UComWinnerTab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UComWinnerTab_C>();
	}
};
DUMPER7_ASSERTS_UComWinnerTab_C;

}

