#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortVoiceChannelSpeakerContainer

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FortVoiceChannelSpeakerContainer.FortVoiceChannelSpeakerContainer_C
// 0x0008 (0x02D8 - 0x02D0)
class UFortVoiceChannelSpeakerContainer_C final : public UFortVoiceSpeakerContainerWidget
{
public:
	class UImage*                                 SpeakerIcon;                                       // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FortVoiceChannelSpeakerContainer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FortVoiceChannelSpeakerContainer_C")
	}
	static class UFortVoiceChannelSpeakerContainer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortVoiceChannelSpeakerContainer_C>();
	}
};
DUMPER7_ASSERTS_UFortVoiceChannelSpeakerContainer_C;

}

