#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortVoiceChannelSpeaker

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FortVoiceChannelSpeaker.FortVoiceChannelSpeaker_C
// 0x0020 (0x02E8 - 0x02C8)
class UFortVoiceChannelSpeaker_C final : public UFortVoiceChannelSpeakerWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       AnimateVoice;                                      // 0x02D0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UBorder*                                Border_OnlineStatusIndicator;                      // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         Content;                                           // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void OnStyleAssigned(EChannelSpeakerStyle NewStyle);
	void PreConstruct(bool IsDesignTime);
	void OnAnimateTalkingChanged(bool bIsNowTalking);
	void ExecuteUbergraph_FortVoiceChannelSpeaker(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FortVoiceChannelSpeaker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FortVoiceChannelSpeaker_C")
	}
	static class UFortVoiceChannelSpeaker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortVoiceChannelSpeaker_C>();
	}
};
DUMPER7_ASSERTS_UFortVoiceChannelSpeaker_C;

}

