#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_JollyRascal

#include "Basic.hpp"

#include "GA_Athena_JollyRascal_classes.hpp"
#include "GA_Athena_JollyRascal_parameters.hpp"


namespace SDK
{

// Function GA_Athena_JollyRascal.GA_Athena_JollyRascal_C.ExecuteUbergraph_GA_Athena_JollyRascal
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Athena_JollyRascal_C::ExecuteUbergraph_GA_Athena_JollyRascal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_JollyRascal_C", "ExecuteUbergraph_GA_Athena_JollyRascal");

	Params::GA_Athena_JollyRascal_C_ExecuteUbergraph_GA_Athena_JollyRascal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Athena_JollyRascal.GA_Athena_JollyRascal_C.OnProjectileSpawned
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortProjectileBase*              SpawnedProjectile_0                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Athena_JollyRascal_C::OnProjectileSpawned(class AFortProjectileBase* SpawnedProjectile_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_JollyRascal_C", "OnProjectileSpawned");

	Params::GA_Athena_JollyRascal_C_OnProjectileSpawned Parms{};

	Parms.SpawnedProjectile_0 = SpawnedProjectile_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

