#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_Bush_AimBlocker

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_Bush_AimBlocker.GA_Athena_Bush_AimBlocker_C
// 0x0008 (0x0948 - 0x0940)
class UGA_Athena_Bush_AimBlocker_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0940(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_Athena_Bush_AimBlocker(int32 EntryPoint);
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void OnAutoAimConditionFailed_DAE3D7A14BF375522FC0189336FE18CC();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Athena_Bush_AimBlocker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Athena_Bush_AimBlocker_C")
	}
	static class UGA_Athena_Bush_AimBlocker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_Bush_AimBlocker_C>();
	}
};
DUMPER7_ASSERTS_UGA_Athena_Bush_AimBlocker_C;

}

