#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Ranged_GenericProjectile_Hit_And_Explosive_Cannon

#include "Basic.hpp"

#include "GA_Ranged_GenericProjectileExplosive_Medium_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Ranged_GenericProjectile_Hit_And_Explosive_Cannon.GA_Ranged_GenericProjectile_Hit_And_Explosive_Cannon_C
// 0x0000 (0x0988 - 0x0988)
class UGA_Ranged_GenericProjectile_Hit_And_Explosive_Cannon_C final : public UGA_Ranged_GenericProjectileExplosive_Medium_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Ranged_GenericProjectile_Hit_And_Explosive_Cannon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Ranged_GenericProjectile_Hit_And_Explosive_Cannon_C")
	}
	static class UGA_Ranged_GenericProjectile_Hit_And_Explosive_Cannon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Ranged_GenericProjectile_Hit_And_Explosive_Cannon_C>();
	}
};
DUMPER7_ASSERTS_UGA_Ranged_GenericProjectile_Hit_And_Explosive_Cannon_C;

}

