#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNL_Athena_Ostrich_Jump_Charging

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCNL_Athena_Ostrich_Jump_Charging.GCNL_Athena_Ostrich_Jump_Charging_C
// 0x0020 (0x0788 - 0x0768)
class AGCNL_Athena_Ostrich_Jump_Charging_C final : public AFortGameplayCueNotify_Loop
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0768(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class UAudioComponent*>                ChargeAudioComps;                                  // 0x0770(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	class UAudioComponent*                        ChargeJumpSound;                                   // 0x0780(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnLoopingStart(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UParticleSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents);
	void OnApplication(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UParticleSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance);
	void OnRemoval(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UParticleSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance);
	void ExecuteUbergraph_GCNL_Athena_Ostrich_Jump_Charging(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCNL_Athena_Ostrich_Jump_Charging_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCNL_Athena_Ostrich_Jump_Charging_C")
	}
	static class AGCNL_Athena_Ostrich_Jump_Charging_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCNL_Athena_Ostrich_Jump_Charging_C>();
	}
};
DUMPER7_ASSERTS_AGCNL_Athena_Ostrich_Jump_Charging_C;

}

