#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Athena_Explosion_Damage

#include "Basic.hpp"

#include "GET_DirectBallisticDamage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Athena_Explosion_Damage.GE_Athena_Explosion_Damage_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_Athena_Explosion_Damage_C : public UGET_DirectBallisticDamage_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Athena_Explosion_Damage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Athena_Explosion_Damage_C")
	}
	static class UGE_Athena_Explosion_Damage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Athena_Explosion_Damage_C>();
	}
};
DUMPER7_ASSERTS_UGE_Athena_Explosion_Damage_C;

}

