#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Ostrich_SelfDestruct

#include "Basic.hpp"

#include "Get_DirectDamageParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Ostrich_SelfDestruct.GE_Ostrich_SelfDestruct_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_Ostrich_SelfDestruct_C final : public UGet_DirectDamageParent_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Ostrich_SelfDestruct_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Ostrich_SelfDestruct_C")
	}
	static class UGE_Ostrich_SelfDestruct_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Ostrich_SelfDestruct_C>();
	}
};
DUMPER7_ASSERTS_UGE_Ostrich_SelfDestruct_C;

}

