#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Quest_Damage_AfterLaunchpad_Tag

#include "Basic.hpp"

#include "GE_Quest_TagCarrier_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Quest_Damage_AfterLaunchpad_Tag.GE_Quest_Damage_AfterLaunchpad_Tag_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_Quest_Damage_AfterLaunchpad_Tag_C final : public UGE_Quest_TagCarrier_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Quest_Damage_AfterLaunchpad_Tag_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Quest_Damage_AfterLaunchpad_Tag_C")
	}
	static class UGE_Quest_Damage_AfterLaunchpad_Tag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Quest_Damage_AfterLaunchpad_Tag_C>();
	}
};
DUMPER7_ASSERTS_UGE_Quest_Damage_AfterLaunchpad_Tag_C;

}

