#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IbmStreamingMediaFactory

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class IbmStreamingMediaFactory.IbmMediaSettings
// 0x0000 (0x0028 - 0x0028)
class UIbmMediaSettings final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("IbmMediaSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"IbmMediaSettings")
	}
	static class UIbmMediaSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UIbmMediaSettings>();
	}
};
DUMPER7_ASSERTS_UIbmMediaSettings;

}

