#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mech_Veh_AmmoFeed_ControlRig

#include "Basic.hpp"

#include "ControlRig_structs.hpp"
#include "ControlRig_classes.hpp"


namespace SDK
{

// ControlRigBlueprintGeneratedClass Mech_Veh_AmmoFeed_ControlRig.Mech_Veh_AmmoFeed_ControlRig_C
// 0x00E8 (0x0360 - 0x0278)
class UMech_Veh_AmmoFeed_ControlRig_C final : public UControlRig
{
public:
	struct FRigUnit_BeginExecution                BeginExecution;                                    // 0x0278(0x0040)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         ChainSlide;                                        // 0x02B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2BC[0x4];                                      // 0x02BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRigUnit_SlideChain                    SlideChain;                                        // 0x02C0(0x00A0)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Mech_Veh_AmmoFeed_ControlRig_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Mech_Veh_AmmoFeed_ControlRig_C")
	}
	static class UMech_Veh_AmmoFeed_ControlRig_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMech_Veh_AmmoFeed_ControlRig_C>();
	}
};
DUMPER7_ASSERTS_UMech_Veh_AmmoFeed_ControlRig_C;

}

