#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MinimalChallengeEntry

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MinimalChallengeEntry.MinimalChallengeEntry_C
// 0x0010 (0x0248 - 0x0238)
class UMinimalChallengeEntry_C final : public UAthenaMinimalChallengeInfoEntry
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0238(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonWidgetSwitcher*                  SwitcherProgressInfo;                              // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void OnChallengeInfoSet(bool bIsInProgress);
	void ExecuteUbergraph_MinimalChallengeEntry(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MinimalChallengeEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MinimalChallengeEntry_C")
	}
	static class UMinimalChallengeEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMinimalChallengeEntry_C>();
	}
};
DUMPER7_ASSERTS_UMinimalChallengeEntry_C;

}

