#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MissionGen_Ashton

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MissionGen_Ashton.MissionGen_Ashton_C
// 0x0000 (0x06C0 - 0x06C0)
class UMissionGen_Ashton_C final : public UFortMissionGenerator
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MissionGen_Ashton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MissionGen_Ashton_C")
	}
	static class UMissionGen_Ashton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMissionGen_Ashton_C>();
	}
};
DUMPER7_ASSERTS_UMissionGen_Ashton_C;

}

