#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OstrichCameraMode_Passenger

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass OstrichCameraMode_Passenger.OstrichCameraMode_Passenger_C
// 0x0000 (0x0CF0 - 0x0CF0)
class UOstrichCameraMode_Passenger_C final : public UFortCameraMode_ThirdPerson
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("OstrichCameraMode_Passenger_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OstrichCameraMode_Passenger_C")
	}
	static class UOstrichCameraMode_Passenger_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOstrichCameraMode_Passenger_C>();
	}
};
DUMPER7_ASSERTS_UOstrichCameraMode_Passenger_C;

}

