#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuestObjectiveData

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct QuestObjectiveData.QuestObjectiveData
// 0x0010 (0x0010 - 0x0000)
struct FQuestObjectiveData final
{
public:
	class UFortQuestItemDefinition*               QuestItemDef_2_99A75A394844F697D1C861BB1C2AD9F0;   // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   BackendObjectiveName_5_D889F49B490546015C0456B21E8F19FC; // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FQuestObjectiveData;

}

