#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: s_pool_floor

#include "Basic.hpp"

#include "_WaterMeshBlueprintMaster_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass s_pool_floor.s_pool_floor_C
// 0x0000 (0x02E0 - 0x02E0)
class As_pool_floor_C final : public A_WaterMeshBlueprintMaster_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("s_pool_floor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"s_pool_floor_C")
	}
	static class As_pool_floor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<As_pool_floor_C>();
	}
};
DUMPER7_ASSERTS_As_pool_floor_C;

}

