#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TabGameOptionsMain

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass TabGameOptionsMain.TabGameOptionsMain_C
// 0x0010 (0x02A0 - 0x0290)
class UTabGameOptionsMain_C final : public UFortGameOptions
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0290(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonTextBlock*                       TooltipDisplayReference;                           // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void UpdateOptionsTab();
	void Construct();
	void CenterOnTab();
	void BndEvt__OptionsListView_K2Node_ComponentBoundEvent_5_OnListViewItemScrolledIntoView__DelegateSignature(class UObject* Item, class UUserWidget* Widget);
	void BndEvt__OptionsListView_K2Node_ComponentBoundEvent_4_OnListViewItemWidgetCreated__DelegateSignature(class UUserWidget* Widget);
	void Setting_Value_Changed(float Value);
	void ExecuteUbergraph_TabGameOptionsMain(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TabGameOptionsMain_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TabGameOptionsMain_C")
	}
	static class UTabGameOptionsMain_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTabGameOptionsMain_C>();
	}
};
DUMPER7_ASSERTS_UTabGameOptionsMain_C;

}

