#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TwitchNotification

#include "Basic.hpp"


namespace SDK::Params
{

// Function TwitchNotification.TwitchNotification_C.GetImageOverride
// 0x0008 (0x0008 - 0x0000)
struct TwitchNotification_C_GetImageOverride final
{
public:
	class UTexture2D*                             ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_TwitchNotification_C_GetImageOverride;

}

