#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIMapManagerCreative

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass UIMapManagerCreative.UIMapManagerCreative_C
// 0x0008 (0x05F8 - 0x05F0)
class AUIMapManagerCreative_C final : public AFortInGameMapManagerCreative
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x05F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UIMapManagerCreative_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UIMapManagerCreative_C")
	}
	static class AUIMapManagerCreative_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AUIMapManagerCreative_C>();
	}
};
DUMPER7_ASSERTS_AUIMapManagerCreative_C;

}

