#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIMapManagerAthena

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass UIMapManagerAthena.UIMapManagerAthena_C
// 0x0008 (0x0598 - 0x0590)
class AUIMapManagerAthena_C final : public AFortInGameMapManagerAthena
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0590(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UIMapManagerAthena_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UIMapManagerAthena_C")
	}
	static class AUIMapManagerAthena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AUIMapManagerAthena_C>();
	}
};
DUMPER7_ASSERTS_AUIMapManagerAthena_C;

}

